# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 02e56ac0321a9056a1586c864eb439d2ca0b16449ba91842b2657744b810c9c907ced0ef6a38b2f2b366e84d59abd1d400a193d148a9b7a6436ca3127cd8dfb8

test:
  secret_key_base: b1b15857934180d7ccac13147071ecf0c39bfbb1d3c4bf43c749e0608d8a3551c47502b133eecdca90f7dedae4b981170419f37c17911be57f1b1391916bdada

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
